import { useEffect } from 'react'
import { aggregateTrophies } from '../../data/trophies'
import { ATTRIBUTE_LABELS, ATTRIBUTE_ORDER } from '../../engine/draft'
import { calculateCareerRating } from '../../engine/rating'
import type { AttributeKey, GameState } from '../../engine/types'
import { formatMoney, stageText, traitText, useI18n } from '../../i18n/config'
import { trackGameEvent, trackGameEventOnce } from '../../lib/analytics'
import { Button } from '../ui/primitives'
import { PlayerShell } from '../ui/PlayerShell'
import { TrophyIcon } from '../ui/TrophyIcon'

function valueText(key: AttributeKey, value: number): string { return key === 'skillMoves' || key === 'weakFoot' ? `${value}★` : String(value) }
function escapeXml(value: string): string { return value.replace(/[<>&'\"]/g, (char) => ({ '<':'&lt;','>':'&gt;','&':'&amp;',"'":'&apos;','"':'&quot;' }[char] ?? char)) }
function downloadBlob(blob: Blob, fileName: string) { const url=URL.createObjectURL(blob); const a=document.createElement('a'); a.href=url; a.download=fileName; a.click(); window.setTimeout(() => URL.revokeObjectURL(url),500) }
async function svgToPng(svg: string, width: number, height: number): Promise<Blob | null> { const source=new Blob([svg],{type:'image/svg+xml;charset=utf-8'}); const url=URL.createObjectURL(source); try { const image=new Image(); image.decoding='async'; const loaded=new Promise<void>((resolve,reject) => { image.onload=() => resolve(); image.onerror=() => reject(new Error('render')) }); image.src=url; await loaded; const canvas=document.createElement('canvas'); canvas.width=width; canvas.height=height; const context=canvas.getContext('2d'); if (!context) return null; context.drawImage(image,0,0,width,height); return await new Promise((resolve) => canvas.toBlob(resolve,'image/png',.94)) } catch { return null } finally { URL.revokeObjectURL(url) } }

export function SummaryPhase({ state, onReplay }: { state: GameState; onReplay: () => void }) {
  const { locale, t } = useI18n()
  const player = state.player
  const rating = player ? calculateCareerRating(state) : null
  useEffect(() => { if (!player || !rating) return; const peak=Math.max(player.peakOverall ?? player.overall,player.overall,...state.seasons.map((s) => s.overall),0); const trophies=state.seasons.reduce((n,s) => n+s.trophies.length,0)+(state.nationalTrophies?.length ?? 0); trackGameEventOnce(`career_finished:${state.seed}`,'career_finished',{ grade:rating.grade, score:rating.score, position:player.position, seasons:state.seasons.length, peak_overall:peak, potential:player.potential, trophies }) },[player,rating,state.seed,state.seasons,state.nationalTrophies])
  if (!player || !rating) return null
  const peakOvr=Math.max(player.peakOverall ?? player.overall,player.overall,...state.seasons.map((s) => s.overall),0)
  const allTrophies=[...state.seasons.flatMap((s) => s.trophies),...(state.nationalTrophies ?? [])]
  const trophyGroups=aggregateTrophies(allTrophies)
  const trophyCount=allTrophies.length
  const ratingLabel=t(rating.label)
  const fileBase=player.lastName.toLowerCase().replace(/[^a-z0-9]+/g,'-') || 'copero'
  const shareText=t('summary.shareText',{ grade:rating.grade, ovr:peakOvr, matches:state.totals.appearances, goals:state.totals.goals, trophies:trophyCount })
  const buildCardSvg=() => { const attrs=ATTRIBUTE_ORDER.map((key,i) => { const x=i%2===0?72:360; const y=390+Math.floor(i/2)*58; return `<text x="${x}" y="${y}" fill="#98a2b3" font-size="16" font-family="monospace">${ATTRIBUTE_LABELS[key].short}</text><text x="${x+70}" y="${y}" fill="#f5f7f2" font-size="27" font-family="Arial" font-weight="900">${escapeXml(valueText(key,player.attributes[key]))}</text>` }).join(''); return `<svg xmlns="http://www.w3.org/2000/svg" width="720" height="920" viewBox="0 0 720 920"><rect width="720" height="920" rx="42" fill="#0b1320"/><rect x="28" y="28" width="664" height="864" rx="34" fill="#111c29" stroke="#d4ad3c" stroke-opacity=".55"/><text x="64" y="90" fill="#d4ad3c" font-size="16" font-family="monospace" font-weight="700">COPERO CAREER RESULT</text><text x="64" y="160" fill="#f5f7f2" font-size="52" font-family="Arial" font-weight="900">${escapeXml((player.lastName || 'COPERO').toUpperCase())}</text><text x="64" y="215" fill="#9eaaae" font-size="21" font-family="Arial">${escapeXml(`${player.nationalityFifa} · ${player.position} · #${player.preferredNumber}`)}</text><text x="64" y="310" fill="#f5f7f2" font-size="82" font-family="Arial" font-weight="900">${rating.grade}</text><text x="190" y="282" fill="#77e36f" font-size="20" font-family="Arial" font-weight="700">OVR ${peakOvr} · POT ${player.potential}</text><text x="190" y="318" fill="#9eaaae" font-size="18" font-family="Arial">${escapeXml(ratingLabel)} · ${rating.score} pts</text>${attrs}<line x1="64" y1="640" x2="656" y2="640" stroke="#ffffff" stroke-opacity=".12"/><text x="64" y="695" fill="#f5f7f2" font-size="22" font-family="Arial" font-weight="700">${escapeXml(t('summary.matches'))} ${state.totals.appearances} · ${escapeXml(t('summary.goals'))} ${state.totals.goals}</text><text x="64" y="735" fill="#f5f7f2" font-size="22" font-family="Arial" font-weight="700">${escapeXml(t('summary.assists'))} ${state.totals.assists} · ${escapeXml(t('summary.trophies'))} ${trophyCount}</text><text x="64" y="805" fill="#d4ad3c" font-size="18" font-family="Arial" font-weight="700">copero.top</text></svg>` }
  const createPng=() => svgToPng(buildCardSvg(),720,920)
  const downloadCard=async() => { const png=await createPng(); if (png) downloadBlob(png,`${fileBase}-career-card.png`); else downloadBlob(new Blob([buildCardSvg()],{type:'image/svg+xml;charset=utf-8'}),`${fileBase}-career-card.svg`); trackGameEvent('result_card_downloaded',{ grade:rating.grade, position:player.position }) }
  const copy=async() => { try { await navigator.clipboard.writeText(shareText); alert(t('summary.copied')) } catch { alert(shareText) } }
  const share=async() => { if (navigator.share) { try { const png=await createPng(); if (png) { const file=new File([png],`${fileBase}-career-card.png`,{type:'image/png'}); if (!navigator.canShare || navigator.canShare({files:[file]})) { await navigator.share({ title:`${player.lastName} · Copero`, text:shareText, files:[file] }); trackGameEvent('result_shared',{method:'native_file',grade:rating.grade}); return } } await navigator.share({ title:`${player.lastName} · Copero`, text:shareText }); trackGameEvent('result_shared',{method:'native_text',grade:rating.grade}); return } catch { /* clipboard fallback */ } } await copy(); trackGameEvent('result_shared',{method:'clipboard',grade:rating.grade}) }
  const left=<div className="brand-result-card p-5 sm:p-6"><div className="flex items-start justify-between gap-5"><div><p className="font-mono text-[10px] font-bold uppercase tracking-[.16em] text-[var(--gold)]">Career Result Card</p><h2 className="mt-2 font-display text-2xl font-black uppercase">{t('summary.finished')}</h2><p className="mt-2 text-sm text-[var(--muted)]">{state.currentEvent?.type === 'retire' ? t(`retire.${state.currentEvent.reason}`) : t('retire.title')}</p></div><div className="text-right"><div className="font-display text-6xl font-black text-[var(--gold)]">{rating.grade}</div><div className="font-mono text-xs text-[var(--muted)]">{rating.score} pts</div></div></div><p className="mt-3 font-display text-lg font-black uppercase">{ratingLabel}</p><p className="mt-1 font-mono text-[11px] uppercase tracking-wide text-[var(--muted)]">{t('summary.maxOvr')} {peakOvr} · {t('summary.potential')} {player.potential} · {stageText(state.careerStage ?? 'local',t)}</p><div className="mt-5 grid grid-cols-4 gap-2">{ATTRIBUTE_ORDER.map((key) => <div key={key} className="rounded-xl border border-[var(--border)] bg-black/20 px-2 py-2 text-center"><div className="font-mono text-[9px] text-[var(--muted)]">{ATTRIBUTE_LABELS[key].short}</div><div className="mt-1 font-display text-base font-black">{valueText(key,player.attributes[key])}</div></div>)}</div><div className="mt-5 grid grid-cols-2 gap-2 sm:grid-cols-4"><Metric label={t('summary.matches')} value={state.totals.appearances} /><Metric label={t('summary.goals')} value={state.totals.goals} /><Metric label={t('summary.assists')} value={state.totals.assists} /><Metric label={t('summary.trophies')} value={trophyCount} /></div><div className="mt-5 grid grid-cols-2 gap-2"><Metric label={t('summary.nationalCareer')} value={state.nationalTotals.appearances} /><Metric label={t('summary.wealth')} value={formatMoney(player.wealth,locale)} /></div>{state.traits.length ? <div className="mt-4 flex flex-wrap gap-1">{state.traits.map((trait) => <span key={trait} className="rounded-full border border-[var(--border)] px-2 py-1 text-[10px] text-[var(--muted)]">{traitText(trait,t).label}</span>)}</div> : null}{trophyGroups.length ? <div className="mt-5 flex flex-wrap gap-3 border-t border-[var(--gold-border)] pt-4">{trophyGroups.map((tr) => <TrophyIcon key={tr.id} src={tr.assetPath} name={tr.name} count={tr.count} className="h-10 w-10" />)}</div> : null}<div className="mt-6 flex flex-wrap gap-2"><Button tone="gold" onClick={downloadCard}>{t('summary.download')}</Button><Button tone="secondary" onClick={share}>{t('summary.share')}</Button><Button tone="secondary" onClick={onReplay}>{t('summary.replay')}</Button></div></div>
  return <PlayerShell state={state} leftExtra={left} />
}

function Metric({ label, value }: { label: string; value: string | number }) { return <div className="rounded-xl border border-[var(--border)] bg-black/20 p-2.5 text-center"><div className="font-mono text-[9px] uppercase text-[var(--muted)]">{label}</div><div className="mt-1 font-display text-lg font-black">{value}</div></div> }
